apiVersion: v1
kind: ConfigMap
metadata:
  name: $SERVICE_NAME-environment-variables
data:
  THIS_SERVICE: $SERVICE_NAME
  BRANCH: $NAMESPACE
  NODE_ENV: production
  PORT: '3100'
  LOG_LEVEL: info
  BACKEND_URL: http://schulcloud-server
  CALENDAR_SERVICE_ENABLED: 'false'
  INSTANCE_NAME: kubectls-experiments.devops-wizard.com
  CORS: 'false'
