apiVersion: v1
kind: ConfigMap
metadata:
  name: $SERVICE_NAME-environment-variables
data:
  THIS_SERVICE: $SERVICE_NAME
  BRANCH: $NAMESPACE
  NODE_ENV: production
  PORT: '3100'
  LOG_LEVEL: info
  BACKEND_URL: http://schulcloud-server
  CALENDAR_SERVICE_ENABLED: 'false'
  SC_DOMAIN: devops-wizard.com
  # must change later for https and cors
  CORS: 'false'
  COOKIE__EXPIRES_SECONDS: "2592000000"
  COOKIE__HOST_ONLY: "false"
  COOKIE__HTTP_ONLY: "false"
  COOKIE__SAME_SITE: Lax
  COOKIE__SECURE: "false"
  COOKIE_SECRET: abc
